version: 3.2.0.{build}
image: Visual Studio 2019
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
nuget:
  disable_publish_on_pr: true
before_build:
- ps: nuget restore src/SAML2.sln
build:
  publish_nuget: true
  publish_nuget_symbols: true
  use_snupkg_format: true
  verbosity: minimal
artifacts:
- path: '**\*nupkg'
- path: src\SAML2\bin\$(configuration)
  name: SAML2-$(appveyor_build_version)
deploy:
- provider: NuGet
  api_key: $(NUGET_API_KEY)
  artifact: /.*(\.|\.s)nupkg/
  skip_symbols: false
  on:
    branch: release
- provider: GitHub
  auth_token: $(GITHUB_API_KEY)
  artifact: src\SAML2\bin\$(configuration)\SAML2-$(appveyor_build_version).zip
  on:
    branch: release